local M = {
  name  = "eddy",
  theme = {
    oxbow = {
      background = "dark",

      palette    = {
        bg           = "#1a2821", -- background surface
        bg_highlight = "#22332b", -- elevated background surface
        fg           = "#e8e3d5", -- primary text
        fg_gutter    = "#82937f", -- subdued UI
        gray         = "#a79f95", -- comments, subdued prose
        blue         = "#adcbe0", -- info, hints, literals
        green        = "#c8dfb8", -- success, strings
        orange       = "#d69f73", -- warnings, attention
        red          = "#c07c72", -- errors, removals
        clay         = "#cc9787", -- keywords, control flow
        yellow       = "#d8c39a", -- types, declarations
      },
    },
  }
}

--- Set highlights for the global namespace.
---
--- @param name string Highlight group name, e.g. "ErrorMsg"
--- @param value vim.api.keyset.highlight Highlight definition map
local function set_highlight(name, value)
  vim.api.nvim_set_hl(0, name, value)
end

--- Link one highlight group to another.
---
--- @param source string Highlight group to link
--- @param target string Highlight group target
local function link_highlight(source, target)
  set_highlight(source, { link = target })
end

--- Setup and apply the color theme.
---
--- @param config table|nil Theme config table.
function M.setup(config)
  config = config or {}
  config.theme = config.theme or "oxbow"

  local theme = M.theme[config.theme]
  if not theme then
    error("invalid theme: " .. tostring(config.theme))
  end

  local palette = theme.palette

  -- Setup
  vim.cmd("highlight clear")
  vim.o.background = theme.background
  vim.g.colors_name = M.name

  -- Editor
  set_highlight("ColorColumn", { bg = palette.bg_highlight })
  set_highlight("Cursor", { bg = palette.fg })
  set_highlight("CursorColumn", { bg = palette.bg_highlight })
  set_highlight("CursorLine", { bg = palette.bg_highlight })
  set_highlight("CursorLineFold", { fg = palette.fg_gutter, bg = palette.bg_highlight })
  set_highlight("CursorLineNr", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("CursorLineSign", { fg = palette.fg_gutter, bg = palette.bg_highlight })
  set_highlight("FloatBorder", { fg = palette.fg_gutter, bg = palette.bg_highlight })
  set_highlight("FloatFooter", { fg = palette.blue, bg = palette.bg_highlight })
  set_highlight("FloatShadow", { bg = palette.bg_highlight, blend = 80 })
  set_highlight("FloatShadowThrough", { bg = palette.bg, blend = 100 })
  set_highlight("FloatTitle", { fg = palette.blue, bg = palette.bg_highlight, bold = true })
  set_highlight("FoldColumn", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("Folded", { fg = palette.fg_gutter, bg = palette.bg_highlight })
  set_highlight("LineNr", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("LineNrAbove", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("LineNrBelow", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("MatchParen", { fg = palette.blue, bold = true, underline = true })
  set_highlight("NonText", { fg = palette.fg_gutter })
  set_highlight("Normal", { fg = palette.fg, bg = palette.bg })
  set_highlight("NormalFloat", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("NormalNC", { fg = palette.fg, bg = palette.bg })
  set_highlight("NormalSB", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("Pmenu", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("PmenuBorder", { fg = palette.fg_gutter, bg = palette.bg_highlight })
  set_highlight("PmenuExtra", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("PmenuExtraSel", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("PmenuKind", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("PmenuKindSel", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("PmenuMatch", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("PmenuMatchSel", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("PmenuSbar", { bg = palette.bg_highlight })
  set_highlight("PmenuSel", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("PmenuShadow", { bg = palette.bg_highlight, blend = 80 })
  set_highlight("PmenuShadowThrough", { bg = palette.bg, blend = 100 })
  set_highlight("PmenuThumb", { bg = palette.fg_gutter })
  set_highlight("SignColumn", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("SpecialKey", { fg = palette.fg_gutter })
  set_highlight("SpellBad", { sp = palette.red, undercurl = true })
  set_highlight("SpellCap", { sp = palette.orange, undercurl = true })
  set_highlight("SpellLocal", { sp = palette.blue, undercurl = true })
  set_highlight("SpellRare", { sp = palette.blue, undercurl = true })
  set_highlight("TermCursor", { fg = palette.bg, bg = palette.fg })
  set_highlight("TermCursorNC", { bg = palette.fg_gutter })
  set_highlight("VertSplit", { fg = palette.fg_gutter })
  set_highlight("Visual", { fg = palette.fg, bg = palette.fg_gutter })
  set_highlight("VisualNOS", { fg = palette.fg, bg = palette.fg_gutter })
  set_highlight("Whitespace", { fg = palette.fg_gutter })
  set_highlight("WinSeparator", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("healthError", { fg = palette.red, bg = palette.bg_highlight })
  set_highlight("healthSuccess", { fg = palette.green, bg = palette.bg_highlight })
  set_highlight("healthWarning", { fg = palette.orange, bg = palette.bg_highlight })
  set_highlight("iCursor", { fg = palette.bg, bg = palette.fg })

  link_highlight("ComplMatchIns", "PmenuMatchSel")
  link_highlight("CursorIM", "Cursor")
  link_highlight("lCursor", "Cursor")

  -- Language
  set_highlight("Annotation", { fg = palette.gray })
  set_highlight("Bold", { bold = true })
  set_highlight("Boolean", { fg = palette.blue })
  set_highlight("Character", { fg = palette.blue })
  set_highlight("Comment", { fg = palette.gray })
  set_highlight("Conceal", { fg = palette.fg_gutter })
  set_highlight("Conditional", { fg = palette.clay })
  set_highlight("Constant", { fg = palette.blue })
  set_highlight("Decorator", { fg = palette.fg })
  set_highlight("Define", { fg = palette.yellow })
  set_highlight("Delimiter", { fg = palette.fg })
  set_highlight("Error", { fg = palette.red })
  set_highlight("Exception", { fg = palette.clay })
  set_highlight("Float", { fg = palette.blue })
  set_highlight("Function", { fg = palette.fg })
  set_highlight("Identifier", { fg = palette.fg })
  set_highlight("Include", { fg = palette.clay })
  set_highlight("Italic", { italic = true })
  set_highlight("Keyword", { fg = palette.clay })
  set_highlight("Label", { fg = palette.fg })
  set_highlight("Number", { fg = palette.blue })
  set_highlight("Operator", { fg = palette.clay })
  set_highlight("PreProc", { fg = palette.clay })
  set_highlight("Repeat", { fg = palette.clay })
  set_highlight("Special", { fg = palette.fg })
  set_highlight("SpecialChar", { fg = palette.fg })
  set_highlight("SpecialComment", { fg = palette.gray })
  set_highlight("Statement", { fg = palette.clay })
  set_highlight("StorageClass", { fg = palette.fg })
  set_highlight("String", { fg = palette.green })
  set_highlight("Structure", { fg = palette.fg })
  set_highlight("Tag", { fg = palette.fg })
  set_highlight("Title", { fg = palette.yellow, bold = true })
  set_highlight("Todo", { fg = palette.orange, bold = true })
  set_highlight("Type", { fg = palette.yellow })
  set_highlight("Typedef", { fg = palette.yellow })
  set_highlight("Underline", { underline = true })

  -- Messages
  set_highlight("ErrorMsg", { fg = palette.fg, bg = palette.red })
  set_highlight("ModeMsg", { fg = palette.fg, bold = true })
  set_highlight("MoreMsg", { fg = palette.blue })
  set_highlight("MsgArea", { fg = palette.fg, bg = palette.bg })
  set_highlight("MsgSeparator", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("OkMsg", { fg = palette.green })
  set_highlight("WarningMsg", { fg = palette.orange })

  -- Markdown
  set_highlight("markdownBlockquote", { fg = palette.gray, bg = palette.bg_highlight, italic = true })
  set_highlight("markdownBoldItalic", { bold = true, italic = true })
  set_highlight("markdownCode", { bg = palette.bg_highlight })
  set_highlight("markdownCodeBlock", { bg = palette.bg_highlight })
  set_highlight("markdownCodeDelimiter", { fg = palette.fg_gutter })
  set_highlight("markdownH2", { fg = palette.clay, bold = true })
  set_highlight("markdownH3", { fg = palette.blue, bold = true })
  set_highlight("markdownH4", { fg = palette.green, bold = true })
  set_highlight("markdownH5", { fg = palette.gray, bold = true })
  set_highlight("markdownH6", { fg = palette.fg_gutter, bold = true, italic = true })
  set_highlight("markdownLinkText", { fg = palette.blue, underline = true })
  set_highlight("markdownListMarker", { fg = palette.green })
  set_highlight("markdownStrike", { fg = palette.fg_gutter, strikethrough = true })
  set_highlight("markdownTaskDone", { fg = palette.green, bold = true })
  set_highlight("markdownTaskTodo", { fg = palette.orange, bold = true })
  set_highlight("markdownUrl", { fg = palette.blue, underline = true })

  link_highlight("markdownBold", "Bold")
  link_highlight("markdownBoldDelimiter", "markdownBold")
  link_highlight("markdownBoldItalicDelimiter", "markdownBoldItalic")
  link_highlight("markdownH1", "Title")
  link_highlight("markdownH1Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownH2Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownH3Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownH4Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownH5Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownH6Delimiter", "markdownHeadingDelimiter")
  link_highlight("markdownHeadingDelimiter", "Delimiter")
  link_highlight("markdownIdDelimiter", "Delimiter")
  link_highlight("markdownItalic", "Italic")
  link_highlight("markdownItalicDelimiter", "markdownItalic")
  link_highlight("markdownLinkDelimiter", "Delimiter")
  link_highlight("markdownOrderedListMarker", "markdownListMarker")
  link_highlight("markdownStrikeDelimiter", "markdownStrike")
  link_highlight("markdownUrlDelimiter", "Delimiter")
  link_highlight("markdownUrlTitleDelimiter", "Delimiter")

  -- Diagnostic
  set_highlight("DiagnosticDeprecated", { fg = palette.fg_gutter, strikethrough = true })
  set_highlight("DiagnosticError", { fg = palette.red })
  set_highlight("DiagnosticHint", { fg = palette.blue, italic = true })
  set_highlight("DiagnosticInfo", { fg = palette.blue })
  set_highlight("DiagnosticLineNrError", { fg = palette.red, bg = palette.bg })
  set_highlight("DiagnosticLineNrHint", { fg = palette.blue, bg = palette.bg })
  set_highlight("DiagnosticLineNrInfo", { fg = palette.blue, bg = palette.bg })
  set_highlight("DiagnosticLineNrOk", { fg = palette.green, bg = palette.bg })
  set_highlight("DiagnosticLineNrWarn", { fg = palette.orange, bg = palette.bg })
  set_highlight("DiagnosticOk", { fg = palette.green })
  set_highlight("DiagnosticUnderlineError", { sp = palette.red, undercurl = true })
  set_highlight("DiagnosticUnderlineHint", { sp = palette.blue, undercurl = true })
  set_highlight("DiagnosticUnderlineInfo", { sp = palette.blue, undercurl = true })
  set_highlight("DiagnosticUnderlineOk", { sp = palette.green, undercurl = true })
  set_highlight("DiagnosticUnderlineWarn", { sp = palette.orange, undercurl = true })
  set_highlight("DiagnosticUnnecessary", { fg = palette.fg_gutter, italic = true })
  set_highlight("DiagnosticVirtualLinesError", { fg = palette.red, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualLinesHint", { fg = palette.blue, bg = palette.bg_highlight, italic = true })
  set_highlight("DiagnosticVirtualLinesInfo", { fg = palette.blue, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualLinesOk", { fg = palette.green, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualLinesWarn", { fg = palette.orange, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualTextError", { fg = palette.red, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualTextHint", { fg = palette.blue, bg = palette.bg_highlight, italic = true })
  set_highlight("DiagnosticVirtualTextInfo", { fg = palette.blue, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualTextOk", { fg = palette.green, bg = palette.bg_highlight })
  set_highlight("DiagnosticVirtualTextWarn", { fg = palette.orange, bg = palette.bg_highlight })
  set_highlight("DiagnosticWarn", { fg = palette.orange })

  link_highlight("DiagnosticFloatingError", "DiagnosticError")
  link_highlight("DiagnosticFloatingHint", "DiagnosticHint")
  link_highlight("DiagnosticFloatingInfo", "DiagnosticInfo")
  link_highlight("DiagnosticFloatingOk", "DiagnosticOk")
  link_highlight("DiagnosticFloatingWarn", "DiagnosticWarn")
  link_highlight("DiagnosticSignError", "DiagnosticError")
  link_highlight("DiagnosticSignHint", "DiagnosticHint")
  link_highlight("DiagnosticSignInfo", "DiagnosticInfo")
  link_highlight("DiagnosticSignOk", "DiagnosticOk")
  link_highlight("DiagnosticSignWarn", "DiagnosticWarn")

  -- StatusLine, WinBar, etc.
  set_highlight("EndOfBuffer", { fg = palette.bg, bg = palette.bg })
  set_highlight("Question", { fg = palette.blue })
  set_highlight("StatusLine", { fg = palette.fg, bg = palette.bg_highlight })
  set_highlight("StatusLineNC", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("WildMenu", { fg = palette.fg, bg = palette.bg_highlight, bold = true })
  set_highlight("WinBar", { fg = palette.fg, bg = palette.bg })
  set_highlight("WinBarNC", { fg = palette.fg_gutter, bg = palette.bg })

  link_highlight("StatusLineTerm", "StatusLine")
  link_highlight("StatusLineTermNC", "StatusLineNC")

  -- Treesitter
  link_highlight("@annotation", "Annotation")
  link_highlight("@attribute", "Decorator")
  link_highlight("@boolean", "Boolean")
  link_highlight("@character", "Character")
  link_highlight("@character.special", "SpecialChar")
  link_highlight("@comment", "Comment")
  link_highlight("@comment.error", "DiagnosticError")
  link_highlight("@comment.note", "DiagnosticInfo")
  link_highlight("@comment.todo", "Todo")
  link_highlight("@comment.warning", "DiagnosticWarn")
  link_highlight("@conditional", "Conditional")
  link_highlight("@constant", "Constant")
  link_highlight("@constant.builtin", "Constant")
  link_highlight("@constant.macro", "Define")
  link_highlight("@constructor", "Function")
  link_highlight("@diff.delta", "DiffChange")
  link_highlight("@diff.minus", "DiffDelete")
  link_highlight("@diff.plus", "DiffAdd")
  link_highlight("@exception", "Exception")
  link_highlight("@field", "Identifier")
  link_highlight("@float", "Float")
  link_highlight("@function", "Function")
  link_highlight("@function.builtin", "Function")
  link_highlight("@function.call", "Function")
  link_highlight("@function.macro", "Define")
  link_highlight("@include", "Include")
  link_highlight("@keyword", "Keyword")
  link_highlight("@keyword.conditional", "Conditional")
  link_highlight("@keyword.conditional.ternary", "Conditional")
  link_highlight("@keyword.coroutine", "Keyword")
  link_highlight("@keyword.debug", "Keyword")
  link_highlight("@keyword.directive", "PreProc")
  link_highlight("@keyword.directive.define", "Define")
  link_highlight("@keyword.exception", "Exception")
  link_highlight("@keyword.function", "Keyword")
  link_highlight("@keyword.import", "Include")
  link_highlight("@keyword.modifier", "StorageClass")
  link_highlight("@keyword.operator", "Operator")
  link_highlight("@keyword.repeat", "Repeat")
  link_highlight("@keyword.return", "Keyword")
  link_highlight("@keyword.storage", "StorageClass")
  link_highlight("@keyword.type", "Type")
  link_highlight("@label", "Label")
  link_highlight("@markup.heading", "markdownH1")
  link_highlight("@markup.heading.1", "markdownH1")
  link_highlight("@markup.heading.2", "markdownH2")
  link_highlight("@markup.heading.3", "markdownH3")
  link_highlight("@markup.heading.4", "markdownH4")
  link_highlight("@markup.heading.5", "markdownH5")
  link_highlight("@markup.heading.6", "markdownH6")
  link_highlight("@markup.italic", "markdownItalic")
  link_highlight("@markup.link", "markdownLinkText")
  link_highlight("@markup.link.label", "markdownLinkText")
  link_highlight("@markup.link.url", "markdownUrl")
  link_highlight("@markup.list", "markdownListMarker")
  link_highlight("@markup.list.checked", "markdownTaskDone")
  link_highlight("@markup.list.unchecked", "markdownTaskTodo")
  link_highlight("@markup.quote", "markdownBlockquote")
  link_highlight("@markup.raw", "markdownCode")
  link_highlight("@markup.raw.block", "markdownCode")
  link_highlight("@markup.raw.delimiter", "markdownCodeDelimiter")
  link_highlight("@markup.strikethrough", "markdownStrike")
  link_highlight("@markup.strong", "markdownBold")
  link_highlight("@markup.underline", "Underline")
  link_highlight("@method", "Function")
  link_highlight("@method.call", "Function")
  link_highlight("@module", "Identifier")
  link_highlight("@module.builtin", "Identifier")
  link_highlight("@number", "Number")
  link_highlight("@operator", "Operator")
  link_highlight("@parameter", "Identifier")
  link_highlight("@parameter.reference", "Identifier")
  link_highlight("@preproc", "PreProc")
  link_highlight("@property", "Identifier")
  link_highlight("@punctuation.bracket", "Delimiter")
  link_highlight("@punctuation.delimiter", "Delimiter")
  link_highlight("@punctuation.special", "SpecialChar")
  link_highlight("@repeat", "Repeat")
  link_highlight("@storageclass", "StorageClass")
  link_highlight("@string", "String")
  link_highlight("@string.escape", "SpecialChar")
  link_highlight("@string.regex", "SpecialChar")
  link_highlight("@string.special", "SpecialChar")
  link_highlight("@string.special.path", "SpecialChar")
  link_highlight("@string.special.symbol", "SpecialChar")
  link_highlight("@string.special.url", "markdownUrl")
  link_highlight("@symbol", "Identifier")
  link_highlight("@tag", "Tag")
  link_highlight("@tag.attribute", "Identifier")
  link_highlight("@tag.delimiter", "Delimiter")
  link_highlight("@text.emphasis", "markdownItalic")
  link_highlight("@text.literal", "markdownCode")
  link_highlight("@text.reference", "markdownLinkText")
  link_highlight("@text.strong", "markdownBold")
  link_highlight("@text.title", "markdownH1")
  link_highlight("@text.todo", "Todo")
  link_highlight("@text.underline", "Underline")
  link_highlight("@text.uri", "markdownUrl")
  link_highlight("@type", "Type")
  link_highlight("@type.builtin", "Type")
  link_highlight("@type.definition", "Typedef")
  link_highlight("@variable", "Identifier")
  link_highlight("@variable.builtin", "Identifier")
  link_highlight("@variable.member", "Identifier")
  link_highlight("@variable.parameter", "Identifier")

  -- LSP
  set_highlight("LspCodeLens", { fg = palette.fg_gutter, italic = true })
  set_highlight("LspInlayHint", { fg = palette.fg_gutter, bg = palette.bg_highlight, italic = true })
  set_highlight("LspReferenceRead", { bg = palette.bg_highlight, underline = true })
  set_highlight("LspReferenceText", { bg = palette.bg_highlight, underline = true })
  set_highlight("LspReferenceWrite", { bg = palette.bg_highlight, underline = true })
  set_highlight("LspSignatureActiveParameter", { fg = palette.blue, underline = true })

  link_highlight("@lsp.mod.deprecated", "DiagnosticDeprecated")
  link_highlight("@lsp.mod.documentation", "@comment")
  link_highlight("@lsp.mod.injected", "@variable")
  link_highlight("@lsp.mod.readonly", "@variable")
  link_highlight("@lsp.type.boolean", "@boolean")
  link_highlight("@lsp.type.class", "@type")
  link_highlight("@lsp.type.comment", "@comment")
  link_highlight("@lsp.type.decorator", "@attribute")
  link_highlight("@lsp.type.enum", "@type")
  link_highlight("@lsp.type.enumMember", "@constant")
  link_highlight("@lsp.type.escapeSequence", "@string.escape")
  link_highlight("@lsp.type.event", "@label")
  link_highlight("@lsp.type.function", "@function")
  link_highlight("@lsp.type.interface", "@type")
  link_highlight("@lsp.type.keyword", "@keyword")
  link_highlight("@lsp.type.macro", "@function.macro")
  link_highlight("@lsp.type.method", "@method")
  link_highlight("@lsp.type.modifier", "@keyword.modifier")
  link_highlight("@lsp.type.namespace", "@module")
  link_highlight("@lsp.type.number", "@number")
  link_highlight("@lsp.type.operator", "@operator")
  link_highlight("@lsp.type.parameter", "@parameter")
  link_highlight("@lsp.type.property", "@property")
  link_highlight("@lsp.type.regexp", "@string.regex")
  link_highlight("@lsp.type.string", "@string")
  link_highlight("@lsp.type.struct", "@type")
  link_highlight("@lsp.type.type", "@type")
  link_highlight("@lsp.type.typeParameter", "@type")
  link_highlight("@lsp.type.variable", "@variable")
  link_highlight("@lsp.typemod.class.defaultLibrary", "@type.builtin")
  link_highlight("@lsp.typemod.enum.defaultLibrary", "@type.builtin")
  link_highlight("@lsp.typemod.enumMember.defaultLibrary", "@constant.builtin")
  link_highlight("@lsp.typemod.function.defaultLibrary", "@function.builtin")
  link_highlight("@lsp.typemod.keyword.async", "@keyword")
  link_highlight("@lsp.typemod.macro.defaultLibrary", "@function.macro")
  link_highlight("@lsp.typemod.method.defaultLibrary", "@function.builtin")
  link_highlight("@lsp.typemod.operator.injected", "@operator")
  link_highlight("@lsp.typemod.string.injected", "@string")
  link_highlight("@lsp.typemod.variable.defaultLibrary", "@variable.builtin")
  link_highlight("@lsp.typemod.variable.global", "@variable")
  link_highlight("@lsp.typemod.variable.injected", "@variable")
  link_highlight("@lsp.typemod.variable.readonly", "@variable")
  link_highlight("@lsp.typemod.variable.static", "@constant")

  -- Navigation
  set_highlight("Directory", { fg = palette.blue })

  -- Search is an interaction state, not a warning state.
  set_highlight("CurSearch", { fg = palette.bg, bg = palette.blue, bold = true })
  set_highlight("IncSearch", { fg = palette.bg, bg = palette.blue, bold = true, underline = true })
  set_highlight("Search", { fg = palette.bg, bg = palette.blue })
  set_highlight("Substitute", { fg = palette.bg, bg = palette.blue, bold = true })

  -- Tab
  set_highlight("TabLine", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("TabLineFill", { fg = palette.fg_gutter, bg = palette.bg })
  set_highlight("TabLineSel", { fg = palette.fg, bg = palette.bg_highlight, bold = true })

  -- Quickfix
  set_highlight("QuickFixLine", { bg = palette.bg_highlight })
  set_highlight("qfFileName", { fg = palette.blue })
  set_highlight("qfLineNr", { fg = palette.fg_gutter })

  -- Snippet
  set_highlight("SnippetTabstop", { bg = palette.bg_highlight, underline = true })
  set_highlight("SnippetTabstopActive", { fg = palette.blue, underline = true })

  -- Diff
  set_highlight("Added", { fg = palette.green })
  set_highlight("Changed", { fg = palette.orange })
  set_highlight("DiffAdd", { fg = palette.green, bg = palette.bg_highlight })
  set_highlight("DiffChange", { fg = palette.orange, bg = palette.bg_highlight })
  set_highlight("DiffDelete", { fg = palette.red, bg = palette.bg_highlight })
  set_highlight("DiffText", { fg = palette.orange, bg = palette.bg_highlight, bold = true })
  set_highlight("Removed", { fg = palette.red })

  link_highlight("DiffTextAdd", "DiffAdd")

  -- Stdin/Stdout
  set_highlight("StdoutMsg", { fg = palette.fg})

  link_highlight("StderrMsg", "ErrorMsg")

  -- MiniPick
  link_highlight("MiniPickBorder", "FloatBorder")
  link_highlight("MiniPickBorderBusy", "FloatTitle")
  link_highlight("MiniPickBorderText", "FloatTitle")
  link_highlight("MiniPickCursor", "Cursor")
  link_highlight("MiniPickHeader", "Title")
  link_highlight("MiniPickIconDirectory", "Directory")
  link_highlight("MiniPickIconFile", "NormalFloat")
  link_highlight("MiniPickMatchCurrent", "PmenuSel")
  link_highlight("MiniPickMatchMarked", "Visual")
  link_highlight("MiniPickMatchRanges", "PmenuMatch")
  link_highlight("MiniPickNormal", "NormalFloat")
  link_highlight("MiniPickPreviewLine", "QuickFixLine")
  link_highlight("MiniPickPreviewRegion", "Visual")
  link_highlight("MiniPickPrompt", "NormalFloat")
  link_highlight("MiniPickPromptCaret", "FloatTitle")
  link_highlight("MiniPickPromptPrefix", "FloatTitle")

  -- MiniDiff
  link_highlight("MiniDiffOverAdd", "DiffAdd")
  link_highlight("MiniDiffOverChange", "DiffChange")
  link_highlight("MiniDiffOverChangeBuf", "DiffText")
  link_highlight("MiniDiffOverContext", "NormalFloat")
  link_highlight("MiniDiffOverContextBuf", "NormalFloat")
  link_highlight("MiniDiffOverDelete", "DiffDelete")
  link_highlight("MiniDiffSignAdd", "Added")
  link_highlight("MiniDiffSignChange", "Changed")
  link_highlight("MiniDiffSignDelete", "Removed")

  -- MiniCompletion
  link_highlight("MiniCompletionActiveParameter", "LspSignatureActiveParameter")
  link_highlight("MiniCompletionDeprecated", "DiagnosticDeprecated")
  link_highlight("MiniCompletionInfoBorderOutdated", "FloatBorder")
end

return M
